"use strict";
// auto-generated by `jswt reexport`
// DO NOT EDIT

module.exports = require("./lib/dashwallet-cli.js")

// these typedef reexports will be available to dependent packages
/**
 * @typedef {import('./bin/dashwallet.js').WalletUtxo} WalletUtxo
 * @typedef {import('./bin/dashwallet.js').WalletUtxoPartial} WalletUtxoPartial
 * @typedef {import('./bin/dashwallet.js').FsStoreConfig} FsStoreConfig
 * @typedef {import('./bin/dashwallet.js').DPayWallets} DPayWallets
 * @typedef {import('./bin/dashwallet.js').DPrivateWallets} DPrivateWallets
 */
